// styles.ts

// ===== SIDEBAR =====
export const sidebarStyles = {
  aside: {
    width: '16rem',
    background: 'linear-gradient(180deg, #0a1628 0%, #0f1e3a 100%)',
    color: 'white',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    height: '100vh',
    position: 'fixed' as const,
    left: 0,
    top: 0,
    zIndex: 50,
    flexShrink: 0,
    borderRight: '1px solid rgba(59, 130, 246, 0.1)',
  },
  logoContainer: {
    padding: '1.5rem',
    paddingBottom: '1rem',
    borderBottom: '1px solid rgba(59, 130, 246, 0.1)',
  },
  logoInner: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
  },
  logoIcon: {
    width: '2.5rem',
    height: '2.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '0.5rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.4)',
  },
  logoTitle: {
    fontSize: '1.125rem',
    fontWeight: 700,
    color: 'white',
    margin: 0,
    letterSpacing: '-0.01em',
  },
  logoSubtitle: {
    fontSize: '0.65rem',
    color: '#94a3b8',
    margin: 0,
  },
  nav: {
    flex: 1,
    padding: '1rem 0.75rem',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '0.25rem',
  },
  menuItem: (isActive: boolean) => ({
    width: '100%',
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.625rem 1rem',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    cursor: 'pointer',
    border: 'none',
    background: isActive
      ? 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)'
      : 'transparent',
    color: isActive ? 'white' : '#cbd5e1',
    transition: 'all 0.2s',
    fontFamily: 'inherit',
    textAlign: 'left' as const,
    boxShadow: isActive ? '0 4px 12px rgba(37, 99, 235, 0.3)' : 'none',
  }),
  adminContainer: {
    padding: '1rem',
    borderTop: '1px solid rgba(59, 130, 246, 0.1)',
  },
  adminInner: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
  },
  adminAvatar: {
    width: '2.5rem',
    height: '2.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '50%',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
    fontWeight: 700,
    color: 'white',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.4)',
  },
  adminName: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'white',
    margin: 0,
  },
  adminEmail: {
    fontSize: '0.7rem',
    color: '#94a3b8',
    margin: 0,
  },
  themeContainer: {
    padding: '1rem',
    borderTop: '1px solid rgba(59, 130, 246, 0.1)',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  themeButton: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.75rem',
    color: '#94a3b8',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    fontFamily: 'inherit',
  },
  themeToggle: {
    width: '2rem',
    height: '1.1rem',
    backgroundColor: '#334155',
    borderRadius: '9999px',
    position: 'relative' as const,
    cursor: 'pointer',
    border: 'none',
    transition: 'backgroundColor 0.2s',
  },
  themeToggleKnob: (isDark: boolean) => ({
    width: '0.8rem',
    height: '0.8rem',
    backgroundColor: 'white',
    borderRadius: '50%',
    position: 'absolute' as const,
    top: '0.15rem',
    left: isDark ? '1rem' : '0.15rem',
    transition: 'left 0.2s',
    boxShadow: '0 1px 2px rgba(0,0,0,0.2)',
  }),
};

// ===== PAGE =====
export const pageStyles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
  },
  mainContent: {
    marginLeft: '16rem',
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
    padding: '0 2rem',
  },
  header: {
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1.5rem 0',
    borderBottom: '1px solid #e2e8f0',
  },
  headerTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
    letterSpacing: '-0.02em',
  },
  headerSubtitle: {
    fontSize: '0.875rem',
    color: '#64748b',
    margin: '0.25rem 0 0',
  },
  headerActions: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
  },
  uploadButton: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    padding: '0.625rem 1.25rem',
    borderRadius: '0.75rem',
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: '0.875rem',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
    transition: 'all 0.2s',
  },
  main: {
    padding: '2rem 0',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '2rem',
  },
};

// ===== METRIC CARDS =====
export const metricCardStyles = {
  container: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '1rem',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: '1rem',
    padding: '1.25rem',
    border: '1px solid #e2e8f0',
    display: 'flex' as const,
    alignItems: 'center',
    gap: '1rem',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    transition: 'all 0.3s',
    cursor: 'default',
  },
  iconContainer: (color: string) => ({
    width: '3rem',
    height: '3rem',
    borderRadius: '0.75rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color,
  }),
  textContainer: {
    flex: 1,
  },
  label: {
    fontSize: '0.75rem',
    color: '#64748b',
    margin: 0,
    fontWeight: 500,
  },
  value: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: '#0f172a',
    margin: '0.25rem 0 0',
    letterSpacing: '-0.02em',
  },
};

// ===== MODULE CARDS =====
export const moduleStyles = {
  card: {
    backgroundColor: 'white',
    borderRadius: '1rem',
    border: '1px solid #e2e8f0',
    padding: '1.5rem',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  cardHeader: {
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '1.5rem',
  },
  cardTitle: {
    fontSize: '1.125rem',
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    letterSpacing: '-0.01em',
  },
  uploadContainer: {
    border: '2px dashed #93c5fd',
    borderRadius: '0.75rem',
    padding: '2.5rem',
    textAlign: 'center' as const,
    backgroundColor: '#eff6ff',
    transition: 'all 0.2s',
    cursor: 'pointer',
  },
  uploadIcon: {
    width: '3rem',
    height: '3rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '50%',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
  },
  uploadText: {
    fontSize: '0.9rem',
    color: '#334155',
    margin: '0.5rem 0 0',
    fontWeight: 600,
  },
  uploadSubtext: {
    fontSize: '0.75rem',
    color: '#94a3b8',
    margin: '0.25rem 0 0',
  },
  uploadButton: {
    marginTop: '1rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    padding: '0.625rem 1.25rem',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    textDecoration: 'none',
    display: 'inline-flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
    border: 'none',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
  },
  uploadFeatures: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '0.75rem',
    marginTop: '1.5rem',
  },
  featureItem: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.75rem',
    color: '#64748b',
    fontWeight: 500,
  },
  docList: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  docItem: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.875rem',
    borderRadius: '0.75rem',
    backgroundColor: '#f8fafc',
    border: '1px solid #f1f5f9',
    transition: 'all 0.2s',
    cursor: 'pointer',
  },
  docIcon: {
    width: '2.5rem',
    height: '2.5rem',
    backgroundColor: '#fee2e2',
    borderRadius: '0.5rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  docInfo: {
    flex: 1,
    minWidth: 0,
  },
  docCode: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#0f172a',
    margin: 0,
  },
  docTitle: {
    fontSize: '0.75rem',
    color: '#64748b',
    margin: '0.25rem 0 0',
  },
  docDate: {
    fontSize: '0.7rem',
    color: '#94a3b8',
    margin: '0.25rem 0 0',
  },
  docMenu: {
    color: '#94a3b8',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: '0.25rem',
    transition: 'color 0.2s',
  },
};

// ===== BUSCAR MODULE =====
export const buscarModuleStyles = {
  container: {
    backgroundColor: 'white',
    borderRadius: '1rem',
    border: '1px solid #e2e8f0',
    padding: '1.5rem',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    width: '100%',
  },
  header: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  title: {
    fontSize: '1.125rem',
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
    letterSpacing: '-0.01em',
  },
  formContainer: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '0.75rem',
    marginBottom: '1rem',
  },
  searchInputContainer: {
    position: 'relative' as const,
    width: '100%',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.25rem',
    fontSize: '0.875rem',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    outline: 'none',
    color: '#0f172a',
    backgroundColor: 'white',
    transition: 'all 0.2s',
  },
  select: {
    width: '100%',
    padding: '0.75rem 1rem',
    fontSize: '0.875rem',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    backgroundColor: 'white',
    color: '#0f172a',
    outline: 'none',
  },
  dateInput: {
    width: '100%',
    padding: '0.75rem 1rem',
    fontSize: '0.875rem',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    backgroundColor: 'white',
    color: '#0f172a',
    outline: 'none',
  },
  searchButton: {
    width: '100%',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    padding: '0.75rem',
    borderRadius: '0.75rem',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.875rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
    transition: 'all 0.2s',
  },
  errorContainer: {
    marginTop: '1rem',
    padding: '0.75rem',
    backgroundColor: '#fef2f2',
    color: '#dc2626',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    border: '1px solid #fecaca',
  },
  resultsContainer: {
    marginTop: '1.5rem',
  },
  resultsTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: '1rem',
  },
  resultItem: {
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    padding: '1rem',
    marginBottom: '0.75rem',
    backgroundColor: 'white',
    transition: 'all 0.2s',
  },
  resultHeader: {
    display: 'flex' as const,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
  },
  resultCode: {
    fontSize: '0.875rem',
    fontWeight: 700,
    color: '#0f172a',
  },
  resultTitle: {
    fontSize: '0.75rem',
    color: '#64748b',
  },
  resultDate: {
    fontSize: '0.75rem',
    color: '#94a3b8',
    marginTop: '0.25rem',
  },
  snippetContainer: {
    backgroundColor: '#f8fafc',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    fontSize: '0.875rem',
    color: '#334155',
    lineHeight: '1.6',
  },
  deleteButton: {
    color: '#94a3b8',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '0.25rem',
  },
};
