// styles.ts

// ===== SIDEBAR =====
export const sidebarStyles = {
  aside: {
    width: '16rem',
    background: 'var(--bg-sidebar)',
    color: 'var(--text-primary)',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    height: '100vh',
    position: 'fixed' as const,
    left: 0,
    top: 0,
    zIndex: 50,
    flexShrink: 0,
    borderRight: '1px solid var(--border-primary)',
    transition: 'background 0.3s, border-color 0.3s',
  },
  logoContainer: {
    padding: '1.5rem 1.25rem',
    borderBottom: '1px solid var(--border-primary)',
  },
  logoInner: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
  },
  logoIcon: {
    width: '2.5rem',
    height: '2.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '0.5rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.4)',
    flexShrink: 0,
  },
  logoTitle: {
    fontSize: '1.125rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
    letterSpacing: '-0.01em',
  },
  logoSubtitle: {
    fontSize: '0.65rem',
    color: 'var(--text-muted)',
    margin: '0.125rem 0 0',
    lineHeight: 1.3,
  },
  nav: {
    flex: 1,
    padding: '1rem 0.75rem',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '0.25rem',
    overflowY: 'auto' as const,
  },
  menuItem: (isActive: boolean) => ({
    width: '100%',
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.75rem 1rem',
    borderRadius: '0.75rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    cursor: 'pointer',
    border: 'none',
    background: isActive
      ? 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)'
      : 'transparent',
    color: isActive ? 'white' : 'var(--text-muted)',
    transition: 'all 0.2s',
    fontFamily: 'inherit',
    textAlign: 'left' as const,
    boxShadow: isActive ? '0 4px 12px rgba(37, 99, 235, 0.3)' : 'none',
  }),
  adminContainer: {
    padding: '1rem',
    borderTop: '1px solid var(--border-primary)',
  },
  adminInner: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.5rem',
    borderRadius: '0.75rem',
    cursor: 'pointer',
  },
  adminAvatar: {
    width: '2.25rem',
    height: '2.25rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '50%',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.875rem',
    fontWeight: 700,
    color: 'white',
    flexShrink: 0,
  },
  adminName: {
    fontSize: '0.8rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  adminEmail: {
    fontSize: '0.65rem',
    color: 'var(--text-muted)',
    margin: '0.125rem 0 0',
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  statusContainer: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1.25rem',
    borderTop: '1px solid var(--border-primary)',
  },
  statusText: {
    fontSize: '0.7rem',
    color: '#10b981',
    fontWeight: 500,
  },
  statusVersion: {
    fontSize: '0.65rem',
    color: 'var(--text-dim)',
    marginLeft: 'auto',
  },
  logoutButton: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
    width: '100%',
    padding: '0.75rem 1.25rem',
    background: 'transparent',
    border: 'none',
    color: 'var(--text-muted)',
    fontSize: '0.875rem',
    fontWeight: 500,
    cursor: 'pointer',
    borderTop: '1px solid var(--border-primary)',
    textAlign: 'left' as const,
    transition: 'all 0.2s',
    fontFamily: 'inherit',
  },
  footerContainer: {
    padding: '1rem 1.25rem',
    borderTop: '1px solid var(--border-primary)',
  },
  footerText: {
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
    margin: 0,
    fontWeight: 600,
    letterSpacing: '0.02em',
  },
  footerSubtext: {
    fontSize: '0.55rem',
    color: 'var(--text-dim)',
    margin: 0,
    letterSpacing: '0.15em',
    fontWeight: 600,
  },
};

// ===== PAGE =====
export const pageStyles = {
  container: {
    minHeight: '100vh',
    background: 'var(--bg-primary)',
    transition: 'background 0.3s',
  },
  mainContent: {
    marginLeft: '16rem',
    minHeight: '100vh',
    background: 'var(--bg-primary)',
    padding: '0 2rem 2rem',
    transition: 'background 0.3s',
  },
  header: {
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1.5rem 0',
    borderBottom: '1px solid var(--border-primary)',
  },
  headerTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
    letterSpacing: '-0.02em',
  },
  headerSubtitle: {
    fontSize: '0.875rem',
    color: 'var(--text-muted)',
    margin: '0.25rem 0 0',
  },
  headerActions: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
  },
  headerIconButton: {
    background: 'var(--bg-card)',
    border: '1px solid var(--border-primary)',
    borderRadius: '0.75rem',
    padding: '0.625rem',
    cursor: 'pointer',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-muted)',
    transition: 'all 0.2s',
  },
  headerAvatar: {
    width: '2.5rem',
    height: '2.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '50%',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.875rem',
    fontWeight: 700,
    color: 'white',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.4)',
  },
  uploadButton: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    padding: '0.625rem 1.25rem',
    borderRadius: '0.75rem',
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: '0.875rem',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
  },
  main: {
    padding: '2rem 0',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
};

// ===== METRIC CARDS =====
export const metricCardStyles = {
  container: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
  },
  card: {
    background: 'var(--bg-card)',
    borderRadius: '1rem',
    padding: '1.25rem',
    border: '1px solid var(--border-primary)',
    display: 'flex' as const,
    alignItems: 'center',
    gap: '1rem',
    transition: 'all 0.3s',
  },
  iconContainer: (color: string) => ({
    width: '3rem',
    height: '3rem',
    borderRadius: '0.75rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    background: color,
    flexShrink: 0,
  }),
  textContainer: {
    flex: 1,
    minWidth: 0,
  },
  label: {
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
    margin: 0,
    fontWeight: 500,
  },
  value: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: '0.25rem 0 0',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '0.65rem',
    color: 'var(--text-dim)',
    margin: '0.125rem 0 0',
  },
  trend: {
    fontSize: '0.7rem',
    fontWeight: 600,
    color: '#10b981',
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.25rem',
    marginLeft: 'auto',
    alignSelf: 'flex-end' as const,
  },
};

// ===== MODULE CARDS =====
export const moduleStyles = {
  card: {
    background: 'var(--bg-card)',
    borderRadius: '1rem',
    border: '1px solid var(--border-primary)',
    padding: '1.5rem',
    transition: 'all 0.3s',
  },
  cardHeader: {
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '1.25rem',
  },
  cardTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    letterSpacing: '-0.01em',
  },
  uploadContainer: {
    border: '2px dashed rgba(59, 130, 246, 0.3)',
    borderRadius: '1rem',
    padding: '2.5rem',
    textAlign: 'center' as const,
    background: 'rgba(30, 58, 95, 0.2)',
    transition: 'all 0.2s',
    cursor: 'pointer',
  },
  uploadIcon: {
    width: '3.5rem',
    height: '3.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '50%',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    boxShadow: '0 8px 24px rgba(37, 99, 235, 0.4)',
  },
  uploadText: {
    fontSize: '0.9rem',
    color: 'var(--text-primary)',
    margin: '0.5rem 0 0',
    fontWeight: 600,
  },
  uploadSubtext: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
    margin: '0.25rem 0 1rem',
  },
  uploadButton: {
    marginTop: '0.5rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    padding: '0.625rem 1.5rem',
    borderRadius: '0.75rem',
    fontSize: '0.8rem',
    fontWeight: 600,
    textDecoration: 'none',
    display: 'inline-flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
    border: 'none',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
  },
  uploadFeatures: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '0.75rem',
    marginTop: '1.25rem',
    paddingTop: '1.25rem',
    borderTop: '1px solid var(--border-primary)',
  },
  featureItem: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
    fontWeight: 500,
  },
  docList: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '0.5rem',
  },
  docItem: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.75rem',
    borderRadius: '0.75rem',
    background: 'var(--bg-card)',
    border: '1px solid var(--border-primary)',
    transition: 'all 0.2s',
    cursor: 'pointer',
  },
  docIcon: {
    width: '2.25rem',
    height: '2.25rem',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    borderRadius: '0.5rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  docInfo: {
    flex: 1,
    minWidth: 0,
  },
  docCode: {
    fontSize: '0.8rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: 0,
  },
  docTitle: {
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
    margin: '0.125rem 0 0',
  },
  docDate: {
    fontSize: '0.65rem',
    color: 'var(--text-dim)',
    margin: '0.125rem 0 0',
  },
  docMenu: {
    color: 'var(--text-dim)',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: '0.25rem',
    transition: 'color 0.2s',
  },
};

// ===== BUSCAR MODULE =====
export const buscarModuleStyles = {
  container: {
    background: 'var(--bg-card)',
    borderRadius: '1rem',
    border: '1px solid var(--border-primary)',
    padding: '1.5rem',
    width: '100%',
    transition: 'all 0.3s',
  },
  header: {
    display: 'flex' as const,
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1.25rem',
  },
  title: {
    fontSize: '1rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    margin: 0,
    letterSpacing: '-0.01em',
  },
  formContainer: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '0.75rem',
  },
  searchInputContainer: {
    position: 'relative' as const,
    width: '100%',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.25rem',
    fontSize: '0.8rem',
    border: '1px solid var(--border-input)',
    borderRadius: '0.75rem',
    outline: 'none',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    transition: 'all 0.2s',
  },
  select: {
    width: '100%',
    padding: '0.75rem 1rem',
    fontSize: '0.8rem',
    border: '1px solid var(--border-input)',
    borderRadius: '0.75rem',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    outline: 'none',
    transition: 'all 0.2s',
  },
  dateInput: {
    width: '100%',
    padding: '0.75rem 1rem',
    fontSize: '0.8rem',
    border: '1px solid var(--border-input)',
    borderRadius: '0.75rem',
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    outline: 'none',
    transition: 'all 0.2s',
  },
  searchButton: {
    width: '100%',
    background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
    color: 'white',
    padding: '0.75rem',
    borderRadius: '0.75rem',
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.8rem',
    display: 'flex' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.3)',
  },
  errorContainer: {
    marginTop: '1rem',
    padding: '0.75rem',
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#fca5a5',
    borderRadius: '0.5rem',
    fontSize: '0.8rem',
    border: '1px solid rgba(239, 68, 68, 0.3)',
  },
  resultsContainer: {
    marginTop: '1.25rem',
  },
  resultsTitle: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    marginBottom: '0.75rem',
  },
  resultItem: {
    border: '1px solid var(--border-primary)',
    borderRadius: '0.75rem',
    padding: '1rem',
    marginBottom: '0.75rem',
    background: 'var(--bg-card)',
  },
  resultHeader: {
    display: 'flex' as const,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '0.5rem',
  },
  resultCode: {
    fontSize: '0.8rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
  },
  resultTitle: {
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
  },
  resultDate: {
    fontSize: '0.7rem',
    color: 'var(--text-dim)',
    marginTop: '0.25rem',
  },
  snippetContainer: {
    background: 'var(--bg-input)',
    padding: '0.75rem',
    borderRadius: '0.5rem',
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    lineHeight: '1.6',
  },
  deleteButton: {
    color: 'var(--text-dim)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '0.25rem',
  },
};
